# Commonly used Numpy operations

In [4]:
import numpy as np

In [5]:
a= np.array([1,2,3,4])
b= np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

In [7]:
type(a)

numpy.ndarray

In [9]:
a

array([ 3.14,  2.  ,  4.  , 13.  ])

In [13]:
a=np.array([3.14, 2,4,13], dtype = 'int') #'int or float

In [14]:
a

array([ 3,  2,  4, 13])

In [15]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [19]:
np.random.normal(10,4,(3,4)) # ortalama 10. std 4, 3e4 luk matrix

array([[13.66103071,  6.43262668,  7.37889639, 10.89446995],
       [ 9.77217591,  6.94482214,  5.11483717,  3.40250396],
       [10.9550941 , 11.61650883, 15.94188109, -0.83516749]])

In [22]:
np.random.randint(0,10,(3,3)) # tamamen rastgele 0 10 arasinda 3 e 3 luk matrix

array([[0, 0, 6],
       [5, 3, 4],
       [9, 3, 6]])

# ndim #
# shape#
# size#
# dtype#


In [8]:
a=np.random.randint(10,size = 10)
a

array([7, 4, 5, 3, 1, 7, 1, 7, 5, 4])

In [27]:
a.ndim

1

In [28]:
a.shape

(10,)

In [29]:
a.size

10

In [30]:
a.dtype

dtype('int32')

In [31]:
b = np.random.randint(10, size = (3,5))
b

array([[9, 7, 6, 3, 9],
       [7, 4, 7, 2, 1],
       [9, 4, 9, 6, 5]])

In [33]:
b.ndim

2

In [34]:
b.size

15

In [35]:
b.dtype

dtype('int32')

## Array reshaping

 #.reshape# ile  Convert 1 dimensional array to 2 dimensional array

In [37]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
a = np.arange(1,10) # a is an array. 1 dimension
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
b = a.reshape(1,9)
b # b is a matrix now. It has 2 dimensions

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
b.ndim

2

In [44]:
b.shape

(1, 9)

In [45]:
b.size

9

## combine arrays (concatenation)

In [47]:
x = np.array([1,2,3])
y = np.array([2,3,4])

In [49]:
np.concatenate([x,y])  

array([1, 2, 3, 2, 3, 4])

# 2 dimensinal concat

In [51]:
c = np.array([[1,2,3],
              [4,5,6]])
c # 2 dimensional array

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.concatenate([c,c]) # combined 2 c arrays in rows

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [56]:
# lets concat in columns
np.concatenate([c,c], axis =1) # combined 2 c arrays in columns

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array splitting

In [57]:
x = np.array([2,3,5,7,89,65,34,32])

In [60]:
a,b,c = np.split(x,[3,5])

In [61]:
a

array([2, 3, 5])

In [62]:
b

array([ 7, 89])

In [63]:
c

array([65, 34, 32])

# 2 dimensional splitting


np.vsplit dikey boler
np.hsplit yatay boler

In [65]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
np.vsplit(m,[2]) # 2 satirdan asagisini ayri bir array yapar

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [67]:
np.hsplit(m,[2]) # 2 sutundan sonra yanini ayri bir array yapar

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# Array sorting

In [68]:
a = np.array([4,2,7,9,4,5,1,0,13])

In [69]:
np.sort(a)

array([ 0,  1,  2,  4,  4,  5,  7,  9, 13])

# 2 dimensional array sorting

In [74]:
m = np.random.normal(20,5,(3,3))
m

array([[17.85232402, 14.5506291 , 13.93297091],
       [14.98087406, 26.74337514, 16.79299147],
       [21.95070919, 18.56233364, 35.37834086]])

In [76]:
np.sort(m, axis = 0) # sorting according to column

array([[14.98087406, 14.5506291 , 13.93297091],
       [17.85232402, 18.56233364, 16.79299147],
       [21.95070919, 26.74337514, 35.37834086]])

In [77]:
np.sort(m, axis = 1) # sorting according to row

array([[13.93297091, 14.5506291 , 17.85232402],
       [14.98087406, 16.79299147, 26.74337514],
       [18.56233364, 21.95070919, 35.37834086]])

# Reach out to indexes

In [78]:
a = np.array([1,3,5,7,9,6,4])

In [79]:
a[1]

3

# Reach out to two dimensional indexes

In [83]:
m = np.random.randint(10, size = (3,5))
m

array([[1, 2, 4, 8, 1],
       [4, 7, 2, 9, 5],
       [6, 4, 6, 9, 2]])

In [85]:
m[0,0]

1

# one dimensional data slicing 

In [88]:
x = np.arange(20,30)
x

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [90]:
x[0:4]

array([20, 21, 22, 23])

In [91]:
x [0::2]

array([20, 22, 24, 26, 28])

In [92]:
x[1::2]

array([21, 23, 25, 27, 29])

# two dimensional slicing

In [94]:
c = np.random.randint(10, size = (5,5))
c

array([[4, 5, 6, 3, 3],
       [4, 9, 0, 6, 2],
       [3, 1, 4, 7, 4],
       [4, 4, 9, 9, 3],
       [9, 8, 0, 0, 3]])

In [99]:
c[:, 0] # sifirinci sutuna eris

array([4, 4, 3, 4, 9])

In [97]:
c[:, 1] #birinci sutune eris

array([5, 9, 1, 4, 8])

In [100]:
c[0, :] # sifirinci satir

array([4, 5, 6, 3, 3])

In [104]:
c[ :4, 0:2] # 0dan 4 e kadar satirlri, 0 adn 2 ye kadar sutunlari alir

array([[4, 5],
       [4, 9],
       [3, 1],
       [4, 4]])

# Operations under an array's subset 

Bazen bir arrayde islem yaparken o arrayi bozmadan baska bir degere atayarak o arrayde islem yapilmak istenebilir.

In [108]:
a = np.random.randint(10, size = (5,5))
a

array([[4, 5, 6, 3, 9],
       [3, 8, 9, 1, 5],
       [9, 7, 0, 6, 0],
       [7, 2, 7, 1, 9],
       [2, 7, 6, 9, 8]])

In [112]:
sub_a = a[0:3, 0:2]
sub_a

array([[4, 5],
       [3, 8],
       [9, 7]])

In [115]:
sub_a[0,0] = 9999
sub_a[1,1] = 888
sub_a

array([[9999,    5],
       [   3,  888],
       [   9,    7]])

In [116]:
# sub_a da yaptigimiz degisiklikler a da da etkili oldu ve degistirdi.
a

array([[9999,    5,    6,    3,    9],
       [   3,  888,    9,    1,    5],
       [   9,    7,    0,    6,    0],
       [   7,    2,    7,    1,    9],
       [   2,    7,    6,    9,    8]])

In [119]:
# ancak biz bunu istemiyoruz. a orjibal haliyle kalsin istiyoruz.
m = np.random.randint(10, size = (5,5))  # arrayi bastan tanimladik
sub_m = m[0:3, 0:2].copy()  # copy methodunu arrayin sonuna bagladigimizda orjinal arrayi bozmadan devam eder
sub_m

array([[8, 1],
       [1, 4],
       [2, 9]])

In [122]:
sub_m[0,0] = 9999  # sub_m in 00 inci indexini degistirdigimiz halde, copy kullandigimiz icin orjinal array ayni kaldi

In [121]:
m

array([[8, 1, 1, 0, 0],
       [1, 4, 1, 1, 2],
       [2, 9, 4, 3, 5],
       [7, 0, 8, 4, 7],
       [7, 0, 5, 8, 7]])

# reach out to elements with fancy index

In [123]:
a = np.arange(0,30,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [125]:
a[1]

3

In [126]:
a[3]

9

In [124]:
a[5]

15

In [127]:
# bu indexlerin hepsine tek satirda ulasmak icin fancy index kullanicaz

In [128]:
bring = [1,3,5]

In [130]:
a[bring]  # bu durumda istedidigimiz 1 3 ve 5 inci indexleri getirir

array([ 3,  9, 15])

In [131]:
# iki boyutta fancy

In [139]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [140]:
row = np.array([0,1])
column = np.array([1,2])

In [141]:
b[row,column]

array([1, 5])

# fancy index creation with simple index

In [144]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [148]:
b [0:, [1,2]]   # slice ile satir sectik, fancy ile sutun ectik

array([[1, 2],
       [4, 5],
       [7, 8]])

# Selective operations

In [150]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [154]:
a[  a < 3]  # 3 ten kucuk olanlari getirir

array([1, 2])

In [155]:
a <  3  # direk bunu yazarsan teua false doner.

array([ True,  True, False, False, False])

# Mathematical Operations

In [156]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [157]:
a -1 # subtract 1 from each elemnts 

array([0, 1, 2, 3, 4])

In [158]:
a * 5 

array([ 5, 10, 15, 20, 25])

In [161]:
np.subtract(a,1)  # arka planda ise subtact fonksiyonu doner ve 1 cikartilir.  asli budur

array([0, 1, 2, 3, 4])

In [ ]:
# add, multiply, divide

In [163]:
a**2  # square of a

array([ 1,  4,  9, 16, 25], dtype=int32)

In [165]:
a**3  # cube of a

array([  1,   8,  27,  64, 125], dtype=int32)

In [167]:
np.power(a,3)  # bu da hepsinin kupunu alir

array([  1,   8,  27,  64, 125], dtype=int32)

In [169]:
a % 2  # ikiye bolumunden kalanlari getirir

array([1, 0, 1, 0, 1], dtype=int32)

In [170]:
np.mod(a,2) # ikiye bolumunden kalanlari getir

array([1, 0, 1, 0, 1], dtype=int32)

In [171]:
# Absolute value

In [178]:
np.absolute(np.array([-3]))  # mutlak degerini alir

array([3])

In [ ]:
#triggonometric

In [179]:
np.sin(360) # cos, tan, cot  

0.9589157234143065

In [180]:
# logaritmic

In [181]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [182]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [183]:
np.log2(a)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

# Statistical

In [184]:
np.mean(a,axis=0)

3.0

np.mean(arr,axis=0) | Returns mean along specific axis
arr.sum() | Returns sum of arr
arr.min() | Returns minimum value of arr
arr.max(axis=0) | Returns maximum value of specific axis
np.var(arr) | Returns the variance of array
np.std(arr,axis=1) | Returns the standard deviation of specific axis
arr.corrcoef() | Returns correlation coefficient of array

In [185]:
a.sum()

15

In [186]:
a.max(axis=0)

5

In [187]:
np.var(a)

2.0