# Pandas serisi olusturmak.....Satir silmek...sutun silmek... yeni sutun eklemek

In [1]:
import pandas as pd

In [2]:
pd.Series([100,33,3,4,5])

0    100
1     33
2      3
3      4
4      5
dtype: int64

In [3]:
seri = pd.Series([100,33,3,4,5])

In [4]:
type(seri)

pandas.core.series.Series

In [5]:
seri.axes  # index nolari 0 dan 5 e kadar. 5 dahil degil.. step te birer birer artiyor demek

[RangeIndex(start=0, stop=5, step=1)]

In [6]:
seri.dtype

dtype('int64')

In [7]:
seri.shape

(5,)

In [8]:
seri.size

5

In [9]:
seri.ndim

1

In [10]:
seri.head(3)

0    100
1     33
2      3
dtype: int64

In [11]:
seri.tail(2)

3    4
4    5
dtype: int64

# eleman islemleri

In [12]:
import numpy as np
a  = np.array([100,334,5,67,83])

In [13]:
seri = pd.Series(a)

In [14]:
seri

0    100
1    334
2      5
3     67
4     83
dtype: int32

In [15]:
seri = pd.Series([121,200,345,543], index = ["reg", "loj", "cart", "rf"])

In [16]:
seri

reg     121
loj     200
cart    345
rf      543
dtype: int64

In [17]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [18]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    345
rf      543
dtype: int64>

In [19]:
seri.values

array([121, 200, 345, 543], dtype=int64)

# Eleman sorgulama

In [20]:
"reg" in seri

True

In [21]:
"a" in seri

False

In [22]:
#fancy eleman

In [23]:
seri[["rf", "reg"]]

rf     543
reg    121
dtype: int64

In [24]:
seri['reg'] = 130   # yeniden atama

In [25]:
seri

reg     130
loj     200
cart    345
rf      543
dtype: int64

In [26]:
seri['reg':'loj']

reg    130
loj    200
dtype: int64

# Pandas dataframe olusturma

In [27]:
l = [23,34,45,56,67,65]

pd.DataFrame(l, columns = ['degisken_ismi'])

degisken_ismi
0             23
1             34
2             45
3             56
4             67
5             65

In [28]:
m = np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# df isimlendirme

In [29]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])  # sutunlara isim koymak
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [30]:
# sutun ismi degistirme

In [31]:
df.columns = ('deg1','deg2','deg3')
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [32]:
type(df)

pandas.core.frame.DataFrame

In [33]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [34]:
df.shape

(3, 3)

In [35]:
df.ndim

2

In [36]:
df.size  # eleman sayisini verir

9

In [37]:
df.values  #  sadece degerleri cekip np arrayine cevirir. baslangicta pd idi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [39]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

# pd eleman islemleri

In [40]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [41]:
dictionary = {'var1' : s1, 'var2' : s2, 'var3' : s3}  # iki nokta ustuste

In [42]:
dictionary

{'var1': array([2, 5, 5, 9, 3]),
 'var2': array([7, 2, 1, 1, 3]),
 'var3': array([8, 1, 2, 1, 8])}

In [43]:
df = pd.DataFrame(dictionary)
df

var1  var2  var3
0     2     7     8
1     5     2     1
2     5     1     2
3     9     1     1
4     3     3     8

In [44]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [45]:
# index degerlerini isimlerini degistirmek

In [46]:
df.index = ['a','b','c','d','e']

In [47]:
df

var1  var2  var3
a     2     7     8
b     5     2     1
c     5     1     2
d     9     1     1
e     3     3     8

In [48]:
df['c':'e']

var1  var2  var3
c     5     1     2
d     9     1     1
e     3     3     8

# df tum satiri silme islemi

In [49]:
df.drop('a', axis = 0)  # a satirini sildik. ancak df uzerine kalici olarak silmedi.

var1  var2  var3
b     5     2     1
c     5     1     2
d     9     1     1
e     3     3     8

In [50]:
df  # yukarda a satirini sildigimiz halde df hala ayni. bunu kalici olarak silmek istersek asagidaki sekilde yapacagiz

var1  var2  var3
a     2     7     8
b     5     2     1
c     5     1     2
d     9     1     1
e     3     3     8

In [51]:
df.drop('a', axis = 0, inplace = True)  # a satirini sildik

In [52]:
df  # kalici olarak silindi

var1  var2  var3
b     5     2     1
c     5     1     2
d     9     1     1
e     3     3     8

In [53]:
# fancy ile iki satiri beraber silmek

In [54]:
l = ['c','e']

In [55]:
df.drop(l, axis = 0)

var1  var2  var3
b     5     2     1
d     9     1     1

# df tum sutunu silme islemi¶

In [56]:
df.drop('var1', axis = 1)  # a satirini sildik

var2  var3
b     2     1
c     1     2
d     1     1
e     3     8

# degiskenler icin sorgulama

In [57]:
'var1' in df

True

# yeni degisken tanimlama.. 

In [58]:
df['var4'] = df['var1'] / df['var2']
df['var4']

b    2.5
c    5.0
d    9.0
e    1.0
Name: var4, dtype: float64

In [59]:
df

var1  var2  var3  var4
b     5     2     1   2.5
c     5     1     2   5.0
d     9     1     1   9.0
e     3     3     8   1.0

In [60]:
# Sutun silmek kalici olarak inplace ile

In [61]:
df.drop('var4', axis = 1, inplace = True)  

In [62]:
df

var1  var2  var3
b     5     2     1
c     5     1     2
d     9     1     1
e     3     3     8

# iki satiri beraber silmek

In [63]:
l = ['var1', 'var2']   # koseli parantez dikkat

In [64]:
df.drop(l, axis = 1)  # iki satiri beraber sildik

var3
b     1
c     2
d     1
e     8

# Gozlem ve degisken secimi   (Loc & iloc)

In [65]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m , columns = ['var1', 'var2','var3'] )

In [66]:
df

var1  var2  var3
0     5     8     7
1    20    23    24
2    22    13    10
3    28     5    16
4    23    24    23
5    19    28    28
6     1    25    15
7    12    21    11
8    24     5    23
9    16     1     2

In [67]:
# loc: secim yapmak icin kullanilir. tanimlandigi sekil ile secer

In [68]:
df.loc[0:3]

var1  var2  var3
0     5     8     7
1    20    23    24
2    22    13    10
3    28     5    16

In [69]:
# iloc: secim yapmak icin kullanilir. alisik olldugumuz indexleme mantigi ile secer

In [70]:
df.iloc[0:3]

var1  var2  var3
0     5     8     7
1    20    23    24
2    22    13    10

In [71]:
df.loc[0:2, 'var3']

0     7
1    24
2    10
Name: var3, dtype: int32

In [72]:
df.iloc[0:3, 0:2]

var1  var2
0     5     8
1    20    23
2    22    13

In [73]:
#    df.iloc[0:3, 'var2'] #  iloc ile var2 yazarak yapilmaz. sadece integer kabul eder iloc.  o yuzden hata verir

# sadece var3 sutunu secmek icin

In [74]:
df.iloc[0:3] ['var3']  

0     7
1    24
2    10
Name: var3, dtype: int32

In [75]:
df.iloc[0:] ['var3']  # tum satirlari ve var 3 sutununu secer

0     7
1    24
2    10
3    16
4    23
5    28
6    15
7    11
8    23
9     2
Name: var3, dtype: int32

In [76]:
df['var1']

0     5
1    20
2    22
3    28
4    23
5    19
6     1
7    12
8    24
9    16
Name: var1, dtype: int32

# sutunda filtreleme yapmak

In [77]:
df[df.var1 > 15]

var1  var2  var3
1    20    23    24
2    22    13    10
3    28     5    16
4    23    24    23
5    19    28    28
8    24     5    23
9    16     1     2

In [78]:
df[df.var1 > 15]['var1']

1    20
2    22
3    28
4    23
5    19
8    24
9    16
Name: var1, dtype: int32

# birden fazla kosul ile filtreleme

In [79]:
df[ (df.var1 > 15)  & (df.var3 < 10)]

var1  var2  var3
9    16     1     2

In [80]:
df[ (df.var1 > 15)] [['var1', 'var2']]

var1  var2
1    20    23
2    22    13
3    28     5
4    23    24
5    19    28
8    24     5
9    16     1

In [86]:
df.loc[ (df.var1 > 15), ['var1', 'var2']]  # var1 in 15 ten buyuk oldugu satirlar icinvar1 ve var2 yi yazdirir

var1  var2
1    20    23
2    22    13
3    28     5
4    23    24
5    19    28
8    24     5
9    16     1

# join islemleri.. dataframe birlestirme

In [97]:
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m , columns = ['var1', 'var2','var3'] )

In [98]:
m = np.random.randint(1,30, size = (5,3))
df2 = df1 + 99

In [99]:
pd.concat([df1,df2])   # satir olarak ekler. index isimleri 0dan 4 e gidiyor ama bunu duzeltmeliyiz

var1  var2  var3
0    15     2    27
1    25    18     9
2     4     6    18
3     7     4    14
4    16     3    24
0   114   101   126
1   124   117   108
2   103   105   117
3   106   103   113
4   115   102   123

In [91]:
?pd.concat

Signature:
pd.concat(
    objs: Union[Iterable[Union[ForwardRef('DataFrame'), ForwardRef('Series')]], Mapping[Union[Hashable, NoneType], Union[ForwardRef('DataFrame'), ForwardRef('Series')]]],
    axis=0,
    join='outer',
    ignore_index: bool = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: bool = False,
    sort: bool = False,
    copy: bool = True,
) -> Union[ForwardRef('DataFrame'), ForwardRef('Series')]
Docstring:
Concatenate pandas objects along a particular axis with optional set logic
along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a dict is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silen

In [103]:
pd.concat([df1,df2], ignore_index = True )  # simdi indexler normale dondu

var1  var2  var3
0    15     2    27
1    25    18     9
2     4     6    18
3     7     4    14
4    16     3    24
5   114   101   126
6   124   117   108
7   103   105   117
8   106   103   113
9   115   102   123

In [105]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [106]:
df2.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [107]:
df2.columns = ['var1', 'var2', 'deg3']

In [108]:
df2

var1  var2  deg3
0   114   101   126
1   124   117   108
2   103   105   117
3   106   103   113
4   115   102   123

In [109]:
df1

var1  var2  var3
0    15     2    27
1    25    18     9
2     4     6    18
3     7     4    14
4    16     3    24

In [114]:
pd.concat([df1,df2])   # iki df deki degiskenler farkli oldugundan boyle birlestirdi..NaN degerleri var.. normalde ayni bilgiyi tasimadigindan boyle bir islem yapilmasi mantikli degildir.

var1  var2  var3   deg3
0    15     2  27.0    NaN
1    25    18   9.0    NaN
2     4     6  18.0    NaN
3     7     4  14.0    NaN
4    16     3  24.0    NaN
0   114   101   NaN  126.0
1   124   117   NaN  108.0
2   103   105   NaN  117.0
3   106   103   NaN  113.0
4   115   102   NaN  123.0

In [118]:
# kesisimlerine gore birlestirelim..var1 ve var2 degiskeni ikisindede ortak
pd.concat([df1,df2], join = 'inner', ignore_index =True) 

var1  var2
0    15     2
1    25    18
2     4     6
3     7     4
4    16     3
5   114   101
6   124   117
7   103   105
8   106   103
9   115   102

In [ ]:
# var3 ve deg3 degiskenlerinin ayni bilgiyi tasidigini dusunerek bunlari birlestirelim

In [119]:
pd.concat([df1,df2], join_axes = [df2.columns], ignore_index =True) 

TypeError: concat() got an unexpected keyword argument 'join_axes'

In [ ]:
# advanced concat operations,, ileri birlestirme islemleri

In [124]:
df1 = pd.DataFrame({'employees' : ['ali', 'veli', 'ayse', 'fatma'], 
                   'group' : ['accounting','engineering', 'engineering', 'HR']})
df1

employees        group
0       ali   accounting
1      veli  engineering
2      ayse  engineering
3     fatma           HR

In [125]:
df2 = pd.DataFrame({'employees' : ['ayse','ali', 'veli', 'fatma'], 
                   'beginning' : ['2010','2009', '2014', '2013']})
df2

employees beginning
0      ayse      2010
1       ali      2009
2      veli      2014
3     fatma      2013

# birebir birlestirme  merge

In [128]:
pd.merge(df1,df2)  # hangisine gore birlestirecegini kendisi otomatik secer

employees        group beginning
0       ali   accounting      2009
1      veli  engineering      2014
2      ayse  engineering      2010
3     fatma           HR      2013

In [130]:
pd.merge(df1,df2, on = 'employees')  # employees baz alarak birlestirir

employees        group beginning
0       ali   accounting      2009
1      veli  engineering      2014
2      ayse  engineering      2010
3     fatma           HR      2013

In [133]:
df3 = pd.merge(df1,df2)
df3

employees        group beginning
0       ali   accounting      2009
1      veli  engineering      2014
2      ayse  engineering      2010
3     fatma           HR      2013

In [134]:
df4 = pd.DataFrame({'group' : ['accounting','engineering', 'HR'], 
                   'manager' : ['mustafa','caner', 'berkcan',]})
df4

group  manager
0   accounting  mustafa
1  engineering    caner
2           HR  berkcan

In [137]:
pd.merge(df3,df4)   # coktan teke.. yani unique olarak yazar her satiri

employees        group beginning  manager
0       ali   accounting      2009  mustafa
1      veli  engineering      2014    caner
2      ayse  engineering      2010    caner
3     fatma           HR      2013  berkcan

In [138]:
# coktan coka merge.. birlestirince cokluyor.

In [139]:
df5 = pd.DataFrame({'group' : ['accounting', 'accounting','engineering', 'engineering', 'HR', 'HR'], 
                   'abilities' : ['math','excell', 'coding','linux', 'excell' , 'management']})
df5

group   abilities
0   accounting        math
1   accounting      excell
2  engineering      coding
3  engineering       linux
4           HR      excell
5           HR  management

In [140]:
pd.merge(df1,df5)

employees        group   abilities
0       ali   accounting        math
1       ali   accounting      excell
2      veli  engineering      coding
3      veli  engineering       linux
4      ayse  engineering      coding
5      ayse  engineering       linux
6     fatma           HR      excell
7     fatma           HR  management